#!/usr/bin/env tsx
/**
 * glossary/*.md  →  glossary/INDEX.md
 *
 *   npm run glossary                 build, verify, write INDEX.md
 *   npm run glossary -- --check      verify, and fail if INDEX.md is stale; write nothing
 *
 * The parent Tao Te Ching project generates its glossary index from the
 * frontmatter of each entry (tools/build_index.py), and this is the same
 * arrangement: the entry is the source of truth, the index is derived from it,
 * and a hand-kept copy of a derivable list is what the inherited
 * `edited-or-generated` principle forbids.
 *
 * No terms.yaml is written. The parent needs one for its lock checker; here the
 * renderings the locks are checked against live in `render:` in trigrams/ and
 * hexagrams/, and `npm run check` reads them there.
 */

import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs'
import { join, resolve } from 'node:path'
import { load } from 'js-yaml'

const ROOT = resolve(__dirname, '..')
const DIR = join(ROOT, 'glossary')
const OUT = join(DIR, 'INDEX.md')
const CHECK_ONLY = process.argv.slice(2).includes('--check')

/** The files in glossary/ that are about the glossary rather than entries in it. */
const NOT_ENTRIES = new Set(['README.md', 'INDEX.md', 'NAMES.md'])
const REQUIRED = ['character', 'pinyin', 'kind', 'render', 'status', 'since'] as const
const STATUSES = new Set(['draft', 'locked'])
/**
 * Trigrams first, because method.md §7 orders the work by frequency and they came
 * first. Only `trigram` exists so far; a kind not listed sorts after these rather
 * than failing, since what the next entries call themselves is not decided here.
 */
const KINDS = ['trigram', 'hexagram']
const kindOrder = (k: string) => (KINDS.includes(k) ? KINDS.indexOf(k) : KINDS.length)

let failures = 0
const fail = (m: string) => {
  console.log(`  ✗ ${m}`)
  failures++
}

type Entry = {
  file: string
  character: string
  pinyin: string
  kind: string
  render: string
  forbidden: string[]
  status: string
  since: string
  occurrences: Record<string, number>
}

function frontmatter(text: string): Record<string, unknown> {
  const m = /^---\r?\n([\s\S]*?)\r?\n---/.exec(text)
  if (!m) throw new Error('no frontmatter')
  return (load(m[1]) ?? {}) as Record<string, unknown>
}

console.log('\nglossary')

const entries: Entry[] = []
for (const file of readdirSync(DIR).filter(f => f.endsWith('.md') && !NOT_ENTRIES.has(f)).sort()) {
  let fm: Record<string, unknown>
  try {
    fm = frontmatter(readFileSync(join(DIR, file), 'utf8'))
  } catch (e) {
    fail(`${file}: ${(e as Error).message}`)
    continue
  }
  const missing = REQUIRED.filter(k => fm[k] == null || fm[k] === '')
  if (missing.length) {
    fail(`${file}: missing ${missing.join(', ')}`)
    continue
  }
  if (!STATUSES.has(String(fm.status))) fail(`${file}: status "${fm.status}" is not draft or locked`)
  if (!file.startsWith(`${fm.character}-`)) fail(`${file}: the filename should begin with its character, ${fm.character}`)
  entries.push({
    file,
    character: String(fm.character),
    pinyin: String(fm.pinyin),
    kind: String(fm.kind),
    render: String(fm.render),
    forbidden: (fm.forbidden as string[] | undefined) ?? [],
    status: String(fm.status),
    // js-yaml reads an unquoted date as a Date.
    since: fm.since instanceof Date ? fm.since.toISOString().slice(0, 10) : String(fm.since),
    occurrences: (fm.occurrences as Record<string, number> | undefined) ?? {},
  })
}

const peak = (e: Entry) => Math.max(0, ...Object.values(e.occurrences))
entries.sort((a, b) =>
  kindOrder(a.kind) - kindOrder(b.kind) || a.kind.localeCompare(b.kind) || peak(b) - peak(a) || a.character.localeCompare(b.character))

const counts = (e: Entry) =>
  Object.entries(e.occurrences).map(([k, n]) => `${n} ${k.replace(/_/g, ' ')}`).join(' · ') || '—'
const locked = entries.filter(e => e.status === 'locked').length

const index = [
  '# Glossary index',
  '',
  '*Generated by `npm run glossary` from the frontmatter of each entry.*',
  '**Never edit this file by hand.** Edit the entry, then rebuild.',
  '',
  `**${entries.length} entries — ${locked} locked, ${entries.length - locked} draft.** Grouped by kind, then by how often the term occurs.`,
  '',
  '*The rendering a reader sees lives in `render:` in [`../trigrams/`](../trigrams/) and [`../hexagrams/`](../hexagrams/);',
  '`npm run check` fails if it disagrees with the entry. What an entry owes is in [`README.md`](README.md).*',
  '',
  '| Term | Say | Kind | Render as | Never | Occurs | Status | Since | Entry |',
  '|---|---|---|---|---|---|---|---|---|',
  ...entries.map(e =>
    `| **${e.character}** | *${e.pinyin}* | ${e.kind} | ${e.render} | ${e.forbidden.map(f => `"${f}"`).join(', ') || '—'} | ${counts(e)} | ${e.status === 'locked' ? '**locked**' : 'draft'} | ${e.since} | [\`${e.file}\`](${e.file}) |`),
  '',
].join('\n')

if (failures) {
  console.log(`\n✗ ${failures} failure(s). Nothing written.\n`)
  process.exit(1)
}

if (CHECK_ONLY) {
  const current = existsSync(OUT) ? readFileSync(OUT, 'utf8') : ''
  if (current !== index) {
    console.log('  ✗ glossary/INDEX.md is stale against the entries — run `npm run glossary`')
    console.log('\n✗ 1 failure(s)\n')
    process.exit(1)
  }
  console.log(`\n✓ glossary — ${entries.length} entries, INDEX.md current\n`)
  process.exit(0)
}

writeFileSync(OUT, index)
console.log(`  ${entries.length} entries — ${locked} locked, ${entries.length - locked} draft`)
console.log('  → glossary/INDEX.md')
console.log('\n✓ glossary verified\n')
