/**
 * **.md  →  generated/iching-data.ts
 *
 * The markdown frontmatter is the source of truth; this file is generated.
 * Same arrangement as the taoteching glossary, where entries are hand-written
 * and terms.yaml is built from them.
 *
 * It is generated into the app rather than read from disk at runtime because
 * the cast happens on the client, and lib/knowledge.ts's fs-from-cwd pattern is
 * server-only. Sixty-four rows is a rounding error in the bundle.
 *
 *   npm run build
 */

import { readFileSync, writeFileSync, readdirSync } from 'node:fs'
import { join, resolve } from 'node:path'
import { load } from 'js-yaml'
import { signatureOf, type Pole, type Place, type Signature } from './signature'

const KNOWLEDGE = resolve(__dirname, '..')
// Emitted here rather than into the application repository, which this
// generator can no longer reach. generated/iching-data.ts is a committed
// copy of this file; update it from here when the cast data changes.
const OUT = resolve(__dirname, '..', 'generated', 'iching-data.ts')

type Row = Record<string, unknown>

/**
 * Frontmatter only. js-yaml rather than gray-matter deliberately: gray-matter is
 * an apps/web dependency, not a root one, and adding a root dep regenerates the
 * shared lockfile — which has silently broken sibling apps' builds here before.
 */
function frontmatter(text: string): Row {
  const m = /^---\r?\n([\s\S]*?)\r?\n---/.exec(text)
  if (!m) throw new Error('no frontmatter')
  return (load(m[1]) ?? {}) as Row
}

function read(dir: string): Row[] {
  const path = join(KNOWLEDGE, dir)
  return readdirSync(path)
    .filter(f => f.endsWith('.md'))
    .sort()
    .map(f => {
      try {
        return frontmatter(readFileSync(join(path, f), 'utf8'))
      } catch (e) {
        throw new Error(`${dir}/${f}: ${(e as Error).message}`)
      }
    })
}

const hexagrams = read('hexagrams')
const trigrams = read('trigrams')

if (hexagrams.length !== 64) throw new Error(`expected 64 hexagrams, found ${hexagrams.length}`)
if (trigrams.length !== 8) throw new Error(`expected 8 trigrams, found ${trigrams.length}`)

// Order by King Wen number rather than trusting filename sort.
hexagrams.sort((a, b) => Number(a.number) - Number(b.number))
hexagrams.forEach((h, i) => {
  if (Number(h.number) !== i + 1) throw new Error(`hexagram ${i + 1} is numbered ${h.number}`)
  if (!/^[01]{6}$/.test(String(h.lines))) throw new Error(`hexagram ${h.number}: bad figure "${h.lines}"`)
})

// Each hexagram's signature is derived here from the trigram data, never read
// from the hexagram's own copy — check-iching.ts holds that copy to this.
const trigramById = new Map(trigrams.map(t => [String(t.id), { id: String(t.id), spectrum: String(t.spectrum), pole: t.pole as Pole }]))

const placeLiteral = (p: Place) => `{ spectrum: ${JSON.stringify(p.spectrum)}, pole: ${JSON.stringify(p.pole)} }`
const signatureLiteral = (s: Signature) =>
  `{ class: ${JSON.stringify(s.class)}, within: ${placeLiteral(s.within)}, without: ${placeLiteral(s.without)} }`

const q = (v: unknown) => (v == null || v === '' ? 'null' : JSON.stringify(String(v)))

const hexRows = hexagrams
  .map(h => {
    const t = h.trigrams as { lower: string; upper: string }
    const lower = trigramById.get(t.lower)
    const upper = trigramById.get(t.upper)
    if (!lower || !upper) throw new Error(`hexagram ${h.number}: no trigram ${lower ? t.upper : t.lower}`)
    const sig = signatureOf(lower, upper)
    return `  { number: ${h.number}, chinese: ${JSON.stringify(h.chinese)}, pinyin: ${JSON.stringify(h.pinyin)}, figure: ${JSON.stringify(h.lines)}, trigrams: { lower: ${JSON.stringify(t.lower)}, upper: ${JSON.stringify(t.upper)} }, signature: ${signatureLiteral(sig)}, render: ${q(h.render)}, status: ${JSON.stringify(h.status)}, judgment: ${q(h.judgment)} },`
  })
  .join('\n')

const triRows = trigrams
  .map(
    t =>
      `  { id: ${JSON.stringify(t.id)}, chinese: ${JSON.stringify(t.chinese)}, pinyin: ${JSON.stringify(t.pinyin)}, figure: ${JSON.stringify(t.lines)}, imageChinese: ${JSON.stringify(t.image_chinese)}, spectrum: ${JSON.stringify(t.spectrum)}, pole: ${JSON.stringify(t.pole)}, oddLine: ${q(t.odd_line)}, render: ${q(t.render)}, status: ${JSON.stringify(t.status)} },`,
  )
  .join('\n')

const lookup = hexagrams.map(h => `  ${JSON.stringify(String(h.lines))}: ${h.number},`).join('\n')

const drafts = hexagrams.filter(h => h.status === 'draft').length

writeFileSync(
  OUT,
  `// GENERATED by scripts/build-iching.ts — do not edit.
// Source of truth: hexagrams/*.md and trigrams/*.md
// Renderings still undrafted: ${drafts} of 64.

export type Hexagram = {
  number: number
  chinese: string
  pinyin: string
  /** Bottom → top, '1' = yang. */
  figure: string
  trigrams: { lower: string; upper: string }
  /**
   * Its place on the four spectrums, derived from its trigrams: \`within\` is the
   * lower, \`without\` the upper. \`doubled\` is one pole twice, \`crossed\` both poles
   * of one spectrum, \`across\` a pole of each of two. See README § The shape of the figures.
   */
  signature: {
    class: 'doubled' | 'crossed' | 'across'
    within: { spectrum: string; pole: 'yang' | 'yin' }
    without: { spectrum: string; pole: 'yang' | 'yin' }
  }
  /** The single word a player sees. Null until the rendering is drafted. */
  render: string | null
  status: string
  judgment: string | null
}

export type Trigram = {
  id: string
  chinese: string
  pinyin: string
  figure: string
  imageChinese: string
  /** The 說卦 ch 3 pair it belongs to, named by the two ids: "qian-kun", "zhen-xun", "kan-li", "gen-dui". */
  spectrum: string
  /** The kind of its odd line — 繫辭下 陽卦多陰: a yang trigram has one yang line among yin. */
  pole: 'yang' | 'yin'
  /** Where the odd line sits — 說卦 ch 10's first, second, third draw. Null for 乾 and 坤, which have none. */
  oddLine: 'bottom' | 'middle' | 'top' | null
  render: string | null
  status: string
}

/** Indexed by King Wen number minus one. */
export const HEXAGRAMS: readonly Hexagram[] = [
${hexRows}
]

export const TRIGRAMS: readonly Trigram[] = [
${triRows}
]

/** Figure string (bottom → top) → King Wen number. */
export const HEXAGRAM_BY_FIGURE: Readonly<Record<string, number>> = {
${lookup}
}
`,
  'utf8',
)

console.log(`wrote ${OUT}`)
console.log(`  64 hexagrams, 8 trigrams — ${drafts} renderings still undrafted`)
